[build]
publish = "/public"
command = "hugo -d public"

[build.environment]
  HUGO_VERSION = "0.167.0"

[context.branch-deploy]
command = "hugo --gc -b $DEPLOY_PRIME_URL"

[context.deploy-preview]
command = "hugo --gc -b $DEPLOY_PRIME_URL"
