name: Quarterly Release

on:
  schedule:
    # Schedule to run at midnight on the 1st of January, April, July, and October
    - cron: "0 0 1 1,4,7,10 *"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repository
      - name: Generate app token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.JINX_APP_ID }}
          private-key: ${{ secrets.JINX_PRIVATE_KEY }}
          owner: rladies

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "Jinx[bot]"
          git config user.email "jinx@rladies.org"

      - name: Create Tag
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          RELEASE="$(date +"%Y").$(date +"%m")"
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV
          git tag -a "$RELEASE" -m "Automatic release $RELEASE"
          git push origin "$RELEASE"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE }}
          name: "Automatic Release ${{ env.RELEASE }}"
          body: "Quarterly release of the R-Ladies guide."
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
