name: Greet New Contributor

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  welcome:
    uses: rladies/jinx/.github/workflows/reusable-welcome-contributor.yml@main
    with:
      extra_message: |
        While you are here, please remember to add yourself to the
        [`.zenodo.json`](.zenodo.json) file so you are credited in the
        next release.
    secrets:
      JINX_APP_ID: ${{ secrets.JINX_APP_ID }}
      JINX_PRIVATE_KEY: ${{ secrets.JINX_PRIVATE_KEY }}
