name: Render acknowledgements

on:
  workflow_dispatch:
  schedule:
    - cron: "5 4 * * sun"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "latest"

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tinytex: true

      - name: Install packages
        run: Rscript -e "install.packages(c('here', 'jsonlite'), repos = 'https://cloud.r-project.org/')"

      - name: Render acknowledgements
        run: quarto content/acknowledgements/_index.en.qmd --to hugo

      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add content/acknowledgements/
          git commit -m "Automated commit by GitHub Actions"  || echo "Nothing to commit"	
          git push
