name: Render acknowledgements

on:
  workflow_dispatch:
  schedule:
    - cron: "5 4 * * sun"

jobs:
  render-acknowledgements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up cURL
        run: sudo apt-get install -y libcurl4-openssl-dev

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "latest"

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tinytex: true

      - name: Install packages
        shell: Rscript {0}
        run: |
          options(repos = c(CRAN = "https://cloud.r-project.org/"))
          install.packages("pak")
          pak::pkg_install(c('here', 'jsonlite', 'rmarkdown', 'knitr'))

      - name: Render acknowledgements
        run: quarto render content/acknowledgements/_index.en.qmd 

      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add content/acknowledgements/
          git commit -m "Automated commit by GitHub Actions"  || echo "Nothing to commit"	
          git push
